version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'java_learning'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'db_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'db_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3310:3306'
