spring.datasource.url=jdbc:mysql://rc1b-m14jo71617p0dtvm.mdb.yandexcloud.net:3306/hotel_booking?useSSL=true
spring.datasource.username=appuser
spring.datasource.password=ibiigor4954
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:mysql://rc1b-m14jo71617p0dtvm.mdb.yandexcloud.net:3306/hotel_booking?useSSL=true
spring.flyway.user=appuser
spring.flyway.password=ibiigor4954

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false


spring.security.user.name=admin
spring.security.user.password=admin

server.port=8081