CREATE TABLE IF NOT EXISTS user_profile (
    username        VARCHAR(100) NOT NULL PRIMARY KEY,
    institution     VARCHAR(255) NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);